# Generated by Django 5.1.5 on 2025-01-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_tansactioncategory_walletaccount_wallettransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='type',
            field=models.CharField(default='debit', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
