# Generated by Django 5.1.5 on 2025-01-25 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_wallettransactions_type_alter_wallettransactions_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='wallettransactions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wallettransactions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallettransactions',
            name='wallet_account',
        ),
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='WalletAccount',
            new_name='Wallet',
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallets', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallets', to='finance.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('type', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('spPerson', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.category')),
                ('userWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.userwallet')),
            ],
        ),
        migrations.DeleteModel(
            name='TansactionCategory',
        ),
        migrations.DeleteModel(
            name='WalletTransactions',
        ),
    ]
