# Generated by Django 5.1.5 on 2025-02-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_category_createdat_payments_createdat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
